services:
  app:
    image: fa-2023
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fa_2023
    ports:
      - "5432:5432"
    volumes:
      - fa_2023_db:/var/lib/postgresql/data
volumes:
  fa_2023_db:
    external: true
