services:
  app:
    image: finance
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - finance_db:/var/lib/postgresql/data
volumes:
  finance_db:
    external: true
