services:
  finance:
    image: registry.mconst.it/finance
    build:
      context: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
    # command: /bin/sh -c "while sleep 1000; do :; done"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - finance_db:/var/lib/postgresql/data
volumes:
  finance_db:
    external: true
